// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    acompanhamento: {
        name: "acompanhamento";
        parameters: {
          /** STRING - use sql.string() */
          vendedor: SQLStringMarker;
        };
        result: Array<{
          /** Nome do vendedor responsavel pela carteira do cliente */
          vendedor: string;
          /** @sqlType BIGINT */
          na_fila: number;
          /** @sqlType BIGINT */
          trabalhados: number;
          /** @sqlType BIGINT */
          vendeu: number;
          /** @sqlType BIGINT */
          vai_pensar: number;
          /** @sqlType BIGINT */
          sem_interesse: number;
          /** @sqlType BIGINT */
          nao_atendeu: number;
        }>;
      };
    fila: {
        name: "fila";
        parameters: {
          /** STRING - use sql.string() */
          vendedor: SQLStringMarker;
        };
        result: Array<{
          /** Nome do vendedor responsavel pela carteira do cliente */
          vendedor: string;
          /** Posicao do cliente na fila DO VENDEDOR (1 = maior score da carteira dele; nao ha cota: a fila eh por score, o row_number so organiza por vendedor) */
          ordem: number;
          /** Id do cliente (mesmo de gold.score_propensao) */
          cliente_id: number;
          /** Razao social do cliente */
          razao_social: string;
          /** Cidade do cliente */
          cidade: string;
          /** Estado (UF) do cliente */
          uf: string;
          /** Nota de propensao a compra do modelo, entre 0 e 1 */
          score: number;
          /** Faixa do score (Fria, Morna, Quente, Muito quente) */
          faixa: string;
          /** Ticket medio historico do cliente, em R$ */
          ticket_medio: number;
          /** Motivo da indicacao em portugues, montado sobre as features com os numeros reais do cliente, para o vendedor falar com contexto */
          motivo: string;
          /** SKU a sugerir: o mais comprado do cliente na marca preferida que ele NAO comprou nos ultimos 90 dias, com o saldo do snapshot mais recente de estoque */
          sugestao: string;
          /** Resultado registrado apos a ligacao: vendeu, vai_pensar, sem_interesse ou nao_atendeu */
          ultimo_status: string;
          /** Quando o registro foi gravado no sistema */
          ultimo_retorno_em: string;
          /** Texto livre do vendedor sobre a conversa */
          ultimo_comentario: string;
        }>;
      };
    kpis_semana: {
        name: "kpis_semana";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType BIGINT */
          contatos: number;
          /** @sqlType BIGINT */
          vendedores: number;
          /** @sqlType DOUBLE */
          receita_esperada: number;
          /** @sqlType DATE */
          referencia: string;
          /** @sqlType BIGINT */
          acertos_top200: number;
          /** @sqlType DOUBLE */
          lift_top200: number;
          /** @sqlType DOUBLE */
          taxa_base: number;
          /** @sqlType BIGINT */
          retornos: number;
          /** @sqlType BIGINT */
          viraram_pedido: number;
        }>;
      };
    vendedores: {
        name: "vendedores";
        parameters: Record<string, never>;
        result: Array<{
          /** Nome do vendedor responsavel pela carteira do cliente */
          vendedor: string;
          /** @sqlType BIGINT */
          contatos: number;
        }>;
      };
  }
}
